<?php
/**
 * @file
 * Attaches jquery-migrate for easier debugging.
 */

/**
 * Implements hook_library_info_alter().
 */
function jquery_migrate_library_info_alter(&$libraries, $module) {
  if ($module == 'system' && !empty($libraries['jquery'])) {
    $module_path = backdrop_get_path('module', 'jquery_migrate');
    $jquery_active = config_get('system.core', 'jquery_version');
    $path = FALSE;

    if ($jquery_active == 'default') {
      // Check compatibility with jQuery 3+.
      // This warns about functionality deprecated in 3.x, and removed in 4.x.
      $path = $module_path . '/libraries/jquery-migrate/jquery-migrate-3.5.2.js';
    }

    if ($path) {
      $libraries['jquery']['js'][$path] = array(
        'group' => JS_LIBRARY,
        'weight' => -19,
      );
    }
  }
}
